# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json
PackageIdentifier: Amazon.AWSCLI
PackageVersion: 2.13.10
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- aws
ReleaseDate: 2023-08-16
AppsAndFeaturesEntries:
- DisplayName: AWS Command Line Interface v2
  DisplayVersion: 2.13.9.0
  ProductCode: "{7F571F5F-2F18-4D84-8055-B97AA87CB903}"
Installers:
- Architecture: x64
  InstallerUrl: https://awscli.amazonaws.com/AWSCLIV2-2.13.10.msi
  InstallerSha256: B80F59F3125C55AF9F9BDEF82C4F6FB2F18983702E820FC170486C1ED9411ACB
  ProductCode: "{370B3D9A-A5A7-4A64-9BB2-2724824877FD}"
ManifestType: installer
ManifestVersion: 1.4.0

